# DB Scan practise
15-apr-25

# Iris flower

# Step 1 - Define the problem

- The problem statement asks whether measurements of floral attributes can be used to identify IRIS flower species

# Step 2 - Collect and Prepare Data(EDA)

In [7]:
import pandas as pd
import seaborn as sns
import numpy as np

## Step 2.1 - Understand the Dataset

In [9]:
iris=sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [13]:
iris.shape

(150, 5)

In [17]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [21]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [23]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## Step 2.2 - Check for Missing Values

In [27]:
iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

## Step 2.3 - Analyze Target Variable

In [34]:
# As target variable is categorical
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

## Step 2.4 - Univariate Analysis (Single Variable)

# Step 3 - Split the Data

# Step 4 – Scale the dataset – if required

# Step 5 - Choose the Algorithm and Build the model

In [42]:
iris_features=iris.iloc[:,0:4]
iris_features.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [50]:
from sklearn.cluster import DBSCAN

In [54]:
model=DBSCAN(min_samples=12, eps=0.5) # min_samples thumb rule is decide this value is take twice or thrice of your no of features
model.fit(iris_features)

DBSCAN(min_samples=12)

# Step 6 -Train the Model

# Step 7 - Evaluate the Model

In [60]:
model.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0, -1,
        1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
       -1,  2,  2, -1, -1, -1, -1, -1,  2,  2,  2, -1, -1,  2,  2, -1, -1,
       -1,  2, -1, -1,  1,  2, -1,  1,  1,  2, -1, -1, -1,  2,  1, -1, -1,
       -1,  2,  1,  2,  2,  2,  1,  2, -1,  2,  1,  2, -1,  1],
      dtype=int64)

- -1 are noise points
- If we observe, we did not mention anywhere to create 3 clusters but model crates automactically. It means model found 3 class.

In [62]:
iris_features['labels']=model.labels_

In [64]:
iris_features

     sepal_length  sepal_width  petal_length  petal_width  labels
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       1
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3      -1
149           5.9          3.0           5.1          1.8       1

[150 rows x 5 columns]

In [ ]:
plt.figure(figsize=(4,3))
sns.scatterplot

In [71]:
grp=iris_features.groupby('labels')
grp.mean()

        sepal_length  sepal_width  petal_length  petal_width
labels
-1          6.397143     2.962857      4.891429     1.657143
 0          4.973913     3.402174      1.471739     0.243478
 1          5.968000     2.814000      4.424000     1.420000
 2          6.600000     3.036842      5.452632     2.089474

In [73]:
# Lets take origonal set to check with model prediction
grp=iris.groupby('species')
grp.mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

- After matching the mean of model prediction and original dataset we mapped the species with class as below
- setosa - 0 class
- versicolor - 1 class
- virginica - 2 class

In [78]:
# lets see the model prediction by using silhout metric
from sklearn.metrics import silhouette_score

In [82]:
sil_scor=silhouette_score(iris_features.iloc[:,0:4],iris_features['labels']) # inpuuts given are all independent variables and dependent  varaibles
sil_scor

0.3286036630954712

In [ ]:
- If silhout score is more than 0 then model is good.
- Silhout score near to one model is more good