# Sentiment analysis

# 47.1) Movie sentiment analysis

In [8]:
import nltk
from nltk.corpus import stopwords
import pandas as pd
import re

In [12]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Pandhari\AppData\Roaming\nltk_data...

True

In [14]:
from nltk.sentiment import SentimentIntensityAnalyzer

In [16]:
sent_ana=SentimentIntensityAnalyzer()

In [18]:
a='This was a disgrace on the screen. An utter waste of time.'

In [20]:
sent_ana.polarity_scores(a)

{'neg': 0.4, 'neu': 0.6, 'pos': 0.0, 'compound': -0.7184}

In [24]:
b='Great movie. Thoroughly enjoyed it'

In [26]:
sent_ana.polarity_scores(b)

{'neg': 0.0, 'neu': 0.281, 'pos': 0.719, 'compound': 0.8268}

In [57]:
def get_vader_analysis(inputtext):
    sent_ana=SentimentIntensityAnalyzer()
    scores=sent_ana.polarity_scores(inputtext)
    if scores['compound']>0:
        return 'pos'
    else: 
        return 'neg'

In [30]:
get_vader_analysis(a)

'negative'

In [32]:
get_vader_analysis(b)

'positive'

# 47.2) Amazon review

In [35]:
import numpy as np
import pandas as pd

In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

In [37]:
df = pd.read_csv('amazonreviews.tsv', sep='\t')
df.head()

  label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [39]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [41]:
df.loc[0]['review']

'Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^'

In [45]:
sid.polarity_scores(df.loc[0]['review'])

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [49]:
get_vader_analysis(df.loc[0]['review'])

'positive'

In [59]:
df['comp_score'] = df['review'].apply(get_vader_analysis)
df

     label                                             review comp_score
0      pos  Stuning even for the non-gamer: This sound tra...        pos
1      pos  The best soundtrack ever to anything.: I'm rea...        pos
2      pos  Amazing!: This soundtrack is my favorite music...        pos
3      pos  Excellent Soundtrack: I truly like this soundt...        pos
4      pos  Remember, Pull Your Jaw Off The Floor After He...        pos
...    ...                                                ...        ...
9995   pos  A revelation of life in small town America in ...        pos
9996   pos  Great biography of a very interesting journali...        pos
9997   neg  Interesting Subject; Poor Presentation: You'd ...        pos
9998   neg  Don't buy: The box looked used and it is obvio...        neg
9999   pos  Beautiful Pen and Fast Delivery.: The pen was ...        pos

[10000 rows x 3 columns]

In [61]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [63]:
accuracy_score(df['label'],df['comp_score'])

0.713

In [65]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.85      0.53      0.65      5097
         pos       0.65      0.90      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.72      0.70     10000
weighted avg       0.75      0.71      0.70     10000

In [67]:
print(confusion_matrix(df['label'],df['comp_score']))

[[2716 2381]
 [ 489 4414]]